spring:
  application:
    name: service-registry

server:
  port: 8761                    # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: localhost         # 指定该Eureka实例的主机名
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#debug: true
