spring:
  application:
    name: data-simulator

server:
  port: 9002                    # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: localhost         # 指定该Eureka实例的主机名
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
