spring:
  application:
    name: data-ingest
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 9001                    # 指定该Eureka实例的端口

eureka:
  instance:
    hostname: localhost         # 指定该Eureka实例的主机名
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

